/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ettprojekt;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Feisal
 */
public class bjudIn extends javax.swing.JFrame {

    /**
     * Creates new form bjudIn
     */
    private InfDB idb;
    private String namn;
    private Integer aID;
    private Integer mID;
    
    
    public bjudIn(InfDB idb, String namn) {
    initComponents();
    this.idb = idb;
    this.namn = namn;
    
    
    }
    
    public bjudIn(InfDB idb) {
    initComponents();
    this.idb = idb;
    this.namn = namn;
    getAnvandare();
    getMoten();
    }
    
    public void getAnvandare () {
    
        try{
            ArrayList<HashMap<String, String>> anvandareList = idb.fetchRows("SELECT USER_ID, FIRST_NAME FROM USERS ");
            for (HashMap<String, String> anvandare : anvandareList) {
                String allanamn = anvandare.get("USER_ID") + " " + anvandare.get("FIRST_NAME");
                anvandarList.addItem(allanamn);
            }
        }
        catch(InfException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        catch(NullPointerException n){
            JOptionPane.showMessageDialog(null, n.getMessage());
        }
    }
    
    public void getMoten () {
    
        try{
            ArrayList<HashMap<String, String>> moteList = idb.fetchRows("SELECT MOTE_ID, TITEL FROM MOTEN ");
            for (HashMap<String, String> mote : moteList) {
                String allamote = mote.get("MOTE_ID") + " " + mote.get("TITEL");
                motenList.addItem(allamote);
            }
        }
        catch(InfException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        catch(NullPointerException n){
            JOptionPane.showMessageDialog(null, n.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        anvandarList = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        motenList = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bjud in användare");

        anvandarList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Välj användare" }));
        anvandarList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anvandarListActionPerformed(evt);
            }
        });

        jButton1.setText("Bjud");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        motenList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Välj möte" }));
        motenList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motenListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 137, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(motenList, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(anvandarList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(anvandarList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(motenList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
                idb.insert("INSERT INTO SKAPAR_MOTE "
                        + "(USER_ID, MOTE_ID) "
                        + "VALUES (" + aID + ","
                        + "'" + mID+ "',"
                        + ")");
                JOptionPane.showMessageDialog(null, "Elev blev registrerad");
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void anvandarListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anvandarListActionPerformed
        Object a = anvandarList.getSelectedItem();
        String anvandare = String.valueOf(a);

        String anvandarID;
        anvandarID = anvandare.split(" ")[0];
        aID = Integer.parseInt(anvandarID);
    }//GEN-LAST:event_anvandarListActionPerformed

    private void motenListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motenListActionPerformed
        Object m = motenList.getSelectedItem();
        String mote = String.valueOf(m);

        String moteID;
        moteID = mote.split(" ")[0];
        mID = Integer.parseInt(moteID);
    }//GEN-LAST:event_motenListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox anvandarList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox motenList;
    // End of variables declaration//GEN-END:variables
}
