/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ettprojekt;

import static ettprojekt.EttProjekt.idb;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import oru.inf.InfException;

/**
 *
 * @author Christoffer
 */
public class bloggLayout extends javax.swing.JFrame {
    
    private inlaggFrame panel;
    
   private Validering val;
   private static String projekt;
   

    


    /**
     * Creates new form bloggLayout
     *
     *
     *
     */
    public bloggLayout() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        panel = new inlaggFrame();
        val = new Validering();
        
        
        
       
      
     

       
    }
    
    public String getProjektNamn() {
        
        return projekt;
    }
    
    public void setProjektNamn() {
        
        projekt = (String) projektBox.getSelectedItem();
        
    }
    
    public void Startsida() {
        try {
            String fraga = "SELECT INLAGG_ID FROM PROJEKT_INLAGG";
            ArrayList<String> allaInlagg = idb.fetchColumn(fraga);
            int antalInlagg = allaInlagg.size();
            
            String fragan = "SELECT TEXT FROM INLAGG JOIN PROJEKT_INLAGG ON INLAGG.INLAGG_ID = PROJEKT_INLAGG.INLAGG_ID";
            ArrayList<String> texter = idb.fetchColumn(fragan);
            
            fragan = "SELECT TITEL FROM INLAGG JOIN PROJEKT_INLAGG ON INLAGG.INLAGG_ID = PROJEKT_INLAGG.INLAGG_ID";
            ArrayList<String> titlar = idb.fetchColumn(fragan);
            
            for (int j = 0; j < antalInlagg; j++) {
                inlaggFrame panel = new inlaggFrame();
                
                panel1.setLayout(new BoxLayout(panel1, BoxLayout.PAGE_AXIS));
                panel1.add(Box.createRigidArea(new Dimension(0, 20)));
                panel1.add(panel);
                panel1.setVisible(true);
                String allaTexter = texter.get(j);
                String allaTitlar = titlar.get(j);
                panel.setText(allaTexter);
                panel.setTitel(allaTitlar);
        
                
            }
            
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postArea = new javax.swing.JScrollPane();
        panel1 = new javax.swing.JPanel();
        projektBox = new javax.swing.JComboBox<>();
        ComboBox.cboxLaggTillProjekt(projektBox);
        jButton1 = new javax.swing.JButton();
        nyttProjekt = new javax.swing.JButton();
        taBortProjekt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 450));

        postArea.setMinimumSize(new java.awt.Dimension(800, 370));
        postArea.setPreferredSize(new java.awt.Dimension(850, 400));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1091, Short.MAX_VALUE)
        );

        postArea.setViewportView(panel1);

        jButton1.setText("Visa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nyttProjekt.setText("Nytt projekt");
        nyttProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyttProjektActionPerformed(evt);
            }
        });

        taBortProjekt.setText("Ta bort projekt");
        taBortProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taBortProjektActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(projektBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nyttProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taBortProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(postArea, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(postArea, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(projektBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(taBortProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nyttProjekt)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setProjektNamn();
        new projektBloggen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nyttProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyttProjektActionPerformed
        new nyttProjekt().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nyttProjektActionPerformed

    private void taBortProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taBortProjektActionPerformed
        try {
          
            if(val.isProjektAgare(projektBox)){
            String projektNamn = (String) projektBox.getSelectedItem();
            String id = "SELECT PROJEKT_ID FROM PROJEKT WHERE PROJEKTNAMN = '" + projektNamn + "'";
            String projektId = idb.fetchSingle(id);
            String fraga2 = "DELETE FROM PROJEKT WHERE PROJEKTNAMN = '" + projektNamn + "'";
            System.out.println(fraga2);
            String fraga1 = "DELETE FROM PROJEKT_INLAGG WHERE PROJEKT_ID = '" + projektId + "'";
            System.out.println(fraga1);
            
            idb.delete(fraga1);
            idb.delete(fraga2);
            ComboBox.cboxLaggTillProjekt(projektBox);
            JOptionPane.showMessageDialog(null, "Projekt har tagits bort");
        } }catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }
    }//GEN-LAST:event_taBortProjektActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton nyttProjekt;
    private javax.swing.JPanel panel1;
    private javax.swing.JScrollPane postArea;
    private javax.swing.JComboBox<String> projektBox;
    private javax.swing.JButton taBortProjekt;
    // End of variables declaration//GEN-END:variables
}
