/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ettprojekt;

import static ettprojekt.EttProjekt.idb;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfException;

/**
 *
 * @author Toaster
 */
public class visaMoten extends javax.swing.JFrame {

    /**
     * Creates new form visaMoten
     */
    public visaMoten() {
        initComponents();
        visaMote();
    }

    private void visaMote() {
        try {
            String datum = Kalender.datumMote;
            labelDatum.setText("Möten på " + datum);
            String fraga = ("SELECT TITEL FROM MOTEN WHERE DATUM = '" + datum + "';");
            ArrayList<String> moten = idb.fetchColumn(fraga);
            String fraga2 = ("SELECT TID FROM MOTEN WHERE DATUM = '" + datum + "';");
            ArrayList<String> moten2 = idb.fetchColumn(fraga2);
            String fraga3 = ("SELECT PLATS FROM MOTEN WHERE DATUM = '" + datum + "';");
            ArrayList<String> moten3 = idb.fetchColumn(fraga3);
            if (!(moten == null)) {
                String svar = "";
                for (int i = 0; i < moten.size(); i++) {
                    svar += (moten.get(i) + " " + moten2.get(i) +" " + moten3.get(i) + "\n");
                }
                txtMoten.setText(svar);
            }
        } catch (InfException ex) {
            Logger.getLogger(visaMoten.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDatum = new javax.swing.JLabel();
        txtMoten = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelDatum.setText("datum");

        txtMoten.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMoten, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDatum))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDatum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMoten, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDatum;
    private java.awt.TextArea txtMoten;
    // End of variables declaration//GEN-END:variables
}
